host=https://reportportal.epam.com/ui/#login
remoteUrl=${REMOTE_URL:http://localhost:4444/wd/hub}
runMode=${RUN_MODE:remote}
headlessMode=${HEADLESS_MODE:true}

#Do not push to credentials
username=username
password=password
