host=http://localhost:8080
remoteUrl=${REMOTE_URL:http://localhost:4444/wd/hub}
runMode=${RUN_MODE:local}
headlessMode=${HEADLESS_MODE:false}

#Do not push to credentials
username=username
password=password
